--------------------------------------------------------
-- Archivo creado  - miércoles-octubre-26-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ESTUDIANTES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ESTUDIANTES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"EDAD" NUMBER(3,0), 
	"SEXO" VARCHAR2(1 BYTE), 
	"CARRERA" VARCHAR2(20 BYTE), 
	"SEMESTRE" NUMBER(2,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ESTUDIANTES
SET DEFINE OFF;
Insert into SYSTEM.ESTUDIANTES (ID,NOMBRE,APELLIDO,EDAD,SEXO,CARRERA,SEMESTRE) values ('1','Cristian','Muñoz','20','M','ING.SISTEMAS','1');
Insert into SYSTEM.ESTUDIANTES (ID,NOMBRE,APELLIDO,EDAD,SEXO,CARRERA,SEMESTRE) values ('2','Pepito','Perez','19','M','ING.SISTEMAS','1');
--------------------------------------------------------
--  DDL for Index ESTUDIANTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ESTUDIANTES_PK" ON "SYSTEM"."ESTUDIANTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ESTUDIANTES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("EDAD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("CARRERA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" MODIFY ("SEMESTRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ESTUDIANTES" ADD CONSTRAINT "ESTUDIANTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
